language: node_js
node_js:
  - lts/dubnium
  - node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: uN8bpFtYIeJusEfpJvm7A3tODZzdDlJiNxUynOCi1egvUKNhVxLIdINRnaD0Gz3xf/65jsnX5+CnMJik/jWkRRge5obcLJz2NLi+MJycgacXTIQV8YV7Zrs9QeDXa306FGiusMB3yzRjF9fta2t5raWVkc3SvINOgOX3ThpA1zQZbfzuCMriGmZWtpBWXbuapjpiNSCU8ZRN4LlcH2YsdTZgPyfPhAEfuZ42IV0KuodG/gKMSwptc6F1NBS+xMRuThVgh6zSOitwteoxT2jDAT0lZ9tkm9MUq8HASqlgYgqNDYBHy21MJ6MgiXzR+qo2aOQY53SM8VZuwgGlVtZyIK7fBJeb3Al+EH5+jodm7PnuOpVNnI/OgDu5/GyRzF05F2jatu1M9qTTYad/qhxyR/PKDTd8LkBIXI8q/GI4s3YKN5dWL5o70mB76mA3VHePq6yXqDxhxRbUK5fG9DgSCTBz/2f8xYAZQD6vEJH/R1iOwQK4ZI8OZORH2hwKneiOLNoLFkeQVGGXlG0PhH4KXQQrgFr1JJpa5pBRYu9AQdUMjtg5hoxucXYXHksh8EU/JpxZ/PmmM/sDpDMx6nauC954Ts00LRgm8S5m8PwnzR3Oz7DCFYvQpWFRLybkNttIk+6OCBs2o8jfoIXq+frhlt/2y5hWZYNYwGHriocnVKY=
  file:
    - 'unist-util-position.js'
    - 'unist-util-position.min.js'
  on:
    tags: true
